package supermart;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import supermart.Employee.Employee_Menu;
import supermart.Sales.Sales_Menu;
import supermart.Stock.Stock_Menu;

public class Login_Form extends javax.swing.JFrame {

    //For Pannel Dragging
    int lastX, lastY;

    //DataBase connection Stuff
    String host = "jdbc:mysql://localhost:3306/supermartdb";
    String usernameDB = "root";
    String passwordDB = "";
    ResultSet res = null;
    Connection con = null;

    public Login_Form() {
        initComponents();

        //Main frame Color
        getContentPane().setBackground(Color.decode("#ffffff"));

        //Password field change * to Alphabets
        txtpass.setEchoChar((char) 0);

        //DB connection on Start
        try {
            con = DriverManager.getConnection(host, usernameDB, passwordDB);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Server Not Found");
            System.exit(0);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        toolbarLogin = new javax.swing.JPanel();
        closebtn = new javax.swing.JButton();
        minbtn = new javax.swing.JButton();
        txtname = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JPanel();
        loginIcon = new javax.swing.JLabel();
        frontIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 196, 130), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        toolbarLogin.setBackground(new java.awt.Color(79, 196, 130));
        toolbarLogin.setForeground(new java.awt.Color(79, 196, 130));
        toolbarLogin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                toolbarLoginMouseDragged(evt);
            }
        });
        toolbarLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                toolbarLoginMousePressed(evt);
            }
        });
        toolbarLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closebtn.setBackground(new java.awt.Color(79, 196, 130));
        closebtn.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        closebtn.setForeground(new java.awt.Color(249, 0, 48));
        closebtn.setText("X");
        closebtn.setBorder(null);
        closebtn.setBorderPainted(false);
        closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtnActionPerformed(evt);
            }
        });
        toolbarLogin.add(closebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 32, 20));

        minbtn.setBackground(new java.awt.Color(79, 196, 130));
        minbtn.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        minbtn.setText("__");
        minbtn.setAlignmentX(0.5F);
        minbtn.setBorder(null);
        minbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        minbtn.setIconTextGap(0);
        minbtn.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        minbtn.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        minbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minbtnActionPerformed(evt);
            }
        });
        toolbarLogin.add(minbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 32, 20));

        jPanel1.add(toolbarLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 30));

        txtname.setBackground(new java.awt.Color(237, 237, 237));
        txtname.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtname.setForeground(new java.awt.Color(153, 153, 153));
        txtname.setText("Username");
        txtname.setBorder(null);
        txtname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnameFocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnameFocusGained(evt);
            }
        });
        jPanel1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 230, 30));

        txtpass.setBackground(new java.awt.Color(237, 237, 237));
        txtpass.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtpass.setForeground(new java.awt.Color(153, 153, 153));
        txtpass.setText("Password");
        txtpass.setBorder(null);
        txtpass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpassFocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpassFocusGained(evt);
            }
        });
        jPanel1.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 220, 30));

        loginBtn.setBackground(new java.awt.Color(79, 196, 130));
        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginBtnMouseReleased(evt);
            }
        });
        loginBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginIcon.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        loginIcon.setForeground(new java.awt.Color(255, 255, 255));
        loginIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login-32.png"))); // NOI18N
        loginIcon.setText("Login");
        loginIcon.setIconTextGap(10);
        loginBtn.add(loginIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 5, -1, -1));

        jPanel1.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 160, 40));

        frontIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login.jpg"))); // NOI18N
        jPanel1.add(frontIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, 430));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 551, 480));

        setSize(new java.awt.Dimension(551, 480));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

// Close button
    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closebtnActionPerformed

    // Minimize Button
    private void minbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minbtnActionPerformed
        this.setState(ICONIFIED);
    }//GEN-LAST:event_minbtnActionPerformed

    // For Pannel Dragging Set
    private void toolbarLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toolbarLoginMousePressed
        lastX = evt.getXOnScreen();
        lastY = evt.getYOnScreen();
    }//GEN-LAST:event_toolbarLoginMousePressed

    // For Pannel Dragging get
    private void toolbarLoginMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toolbarLoginMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        // Move frame by the mouse delta
        setLocation(getLocationOnScreen().x + x - lastX,
                getLocationOnScreen().y + y - lastY);
        lastX = x;
        lastY = y;
    }//GEN-LAST:event_toolbarLoginMouseDragged

    //Text Field Placeholder in + Check
    private void txtnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnameFocusGained
        String s = "Username";
        String a = txtname.getText().toString();
        if ((a.equalsIgnoreCase(s))) {
            txtname.setText("");
        }
    }//GEN-LAST:event_txtnameFocusGained

    //Text Field Placeholder Out + Check
    private void txtnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnameFocusLost
        String s = "";
        String a = txtname.getText().toString();
        if ((a.equalsIgnoreCase(s))) {
            txtname.setText("Username");
        }
    }//GEN-LAST:event_txtnameFocusLost

    //Password Field Placeholder in + Check
    private void txtpassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpassFocusGained
        txtpass.setEchoChar('*');
        if (txtpass.getText().equals("Password")) {
            txtpass.setText("");
        }
    }//GEN-LAST:event_txtpassFocusGained

    //Password Field Placeholder Out + Check
    private void txtpassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpassFocusLost
        if (txtpass.getText().equals("")) {
            txtpass.setText("Password");
            txtpass.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_txtpassFocusLost

//// Login Button Start /////
    // Login Btn Enter Color Change
    private void loginBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseEntered
        loginBtn.setBackground(Color.decode("#339966"));
    }//GEN-LAST:event_loginBtnMouseEntered

    // Login Btn Exited Color Change
    private void loginBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseExited
        loginBtn.setBackground(Color.decode("#4fc482"));
    }//GEN-LAST:event_loginBtnMouseExited

    // Login Btn Pressed Color Change
    private void loginBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMousePressed
        loginBtn.setBackground(Color.decode("#1e5837"));
    }//GEN-LAST:event_loginBtnMousePressed

    // Login Btn Released Color Change
    private void loginBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseReleased
        loginBtn.setBackground(Color.decode("#4fc482"));
    }//GEN-LAST:event_loginBtnMouseReleased

    // Login Btn Clicked Action Performed
    private void loginBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseClicked
        //Data base Connection and Checkups

        String username = txtname.getText().toString();
        String pass = txtpass.getText().toString();

        try {
            Statement st = con.createStatement();
            res = st.executeQuery("select * from loginform where Username='" + username + "' and Password='" + pass + "' ");

            if (res.next()) {

                String adminU = res.getString("Username");
                String adminP = res.getString("Password");

                if (((adminU.equals("admin")) && (adminP.equals("admin"))) && ((adminU.equals(username)) && (adminP.equals(pass)))) {

                    Admin_Menu obj = new Admin_Menu();
                    obj.setVisible(true);
                    this.setVisible(false);
                } else if (((adminU.equals("sales")) && (adminP.equals("sales"))) && ((adminU.equals(username)) && (adminP.equals(pass)))) {

                    Sales_Menu obj = new Sales_Menu();
                    obj.setVisible(true);
                    Sales_Menu.backBtn.setVisible(false);
                    Sales_Menu.logoutLabel.setVisible(true);
                    this.setVisible(false);
                } else if (((adminU.equals("stock")) && (adminP.equals("stock"))) && ((adminU.equals(username)) && (adminP.equals(pass)))) {

                    Stock_Menu obj = new Stock_Menu();
                    obj.setVisible(true);
                    Stock_Menu.backBtn.setVisible(false);
                    Stock_Menu.logoutLabel.setVisible(true);
                    this.setVisible(false);
                } else if (((adminU.equals("employee")) && (adminP.equals("employee"))) && ((adminU.equals(username)) && (adminP.equals(pass)))) {

                    Employee_Menu obj = new Employee_Menu();
                    obj.setVisible(true);
                    Employee_Menu.backBtn.setVisible(false);
                    Employee_Menu.logoutLabel.setVisible(true);
                    this.setVisible(false);
                }
            } else {
                JOptionPane.showMessageDialog(null, "The Username or Passowrd is incorrect");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: Server Not Found");
        }
    }//GEN-LAST:event_loginBtnMouseClicked
//// Login Button End /////

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel browseBtn;
    private javax.swing.JLabel browseIcon;
    private javax.swing.JButton closebtn;
    private javax.swing.JLabel frontIcon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel loginBtn;
    private javax.swing.JLabel loginIcon;
    private javax.swing.JButton minbtn;
    private javax.swing.JPanel searchBtn;
    private javax.swing.JLabel searchIcon;
    private javax.swing.JPanel toolbarLogin;
    private javax.swing.JTextField txtname;
    private javax.swing.JPasswordField txtpass;
    // End of variables declaration//GEN-END:variables
}
