/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package splash_screen;

import java.awt.Color;
import java.awt.SplashScreen;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.UIDefaults;
import javax.swing.UIManager;
import supermart.Login_Form;
import supermart.Login_Form;
import supermart.Employee.Employee_Menu;
import supermart.Sales.Sales_Menu;
import supermart.Stock.Stock_Menu;

/**
 *
 * @author Farhan
 */
public class splashScreen extends javax.swing.JFrame {

    // Variables for Splash Screen
    private Timer t = null;
    private int counter = 0;

    public splashScreen() {
        initComponents();

        //ProgressBar Color
        UIManager.put("nimbus", loadingbar.getForeground());

        //Main frame Color
        getContentPane().setBackground(Color.decode("#ffffff"));

        /// Splash Screen Start ///
        t = new Timer(20, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                counter++;
                loadingbar.setValue(counter);
                if (loadingbar.getValue() < 100) {
                    loadingbar.setValue(loadingbar.getValue() - 1);
                    loadingnum.setText(Integer.toString(counter));
                }
                if (loadingbar.getValue() == 100) {
                    setVisible(false);
                    Login_Form obj = new Login_Form();
                    obj.setVisible(true);
                    t.stop();

                }

            }
        });
        t.start();
       /// Splash Screen End ///

    }

    public void splashBar() {

        try {

            for (int i = 0; i <= 100; i++) {
                Thread.sleep(30);
                loadingnum.setText(Integer.toString(i) + "%");
            }

        } catch (Exception e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loadingnum = new javax.swing.JLabel();
        loadingbar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 196, 130), 5));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loadingnum.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        loadingnum.setForeground(new java.awt.Color(102, 102, 102));
        loadingnum.setText("0%");
        jPanel1.add(loadingnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 40, 40));

        loadingbar.setBackground(new java.awt.Color(0, 0, 0));
        loadingbar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        loadingbar.setForeground(new java.awt.Color(79, 196, 130));
        loadingbar.setBorderPainted(false);
        jPanel1.add(loadingbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 210, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Loading");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 70, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/splashScreenImage.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 366, 255));

        setSize(new java.awt.Dimension(366, 255));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(splashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(splashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(splashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(splashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new splashScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JProgressBar loadingbar;
    public javax.swing.JLabel loadingnum;
    // End of variables declaration//GEN-END:variables
}
